//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTECAM.Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClavesPresupuestales
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public int IdPrograma { get; set; }
        public int IdProyecto { get; set; }
        public int IdActividad { get; set; }
        public int IdPartida { get; set; }
        public int IdCentroCosto { get; set; }
        public int Anio { get; set; }
        public bool Activo { get; set; }
        public decimal PresupuestoEnero { get; set; }
        public decimal PresupuestoFebrero { get; set; }
        public decimal PresupuestoMarzo { get; set; }
        public decimal PresupuestoAbril { get; set; }
        public decimal PresupuestoMayo { get; set; }
        public decimal PresupuestoJunio { get; set; }
        public decimal PresupuestoJulio { get; set; }
        public decimal PresupuestoAgosto { get; set; }
        public decimal PresupuestoSeptiembre { get; set; }
        public decimal PresupuestoOctubre { get; set; }
        public decimal PresupuestoNoviembre { get; set; }
        public decimal PresupuestoDiciembre { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual CentrosCostos CentrosCostos { get; set; }
        public virtual Partidas Partidas { get; set; }
        public virtual Programas Programas { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
