//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTECAM.Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conceptos
    {
        public Conceptos()
        {
            this.DetallesNomina = new HashSet<DetallesNomina>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string ConceptoNomina { get; set; }
        public string ConceptoPresupuesto { get; set; }
        public int IdTipoConcepto { get; set; }
        public string PartidaPresupuestal { get; set; }
        public string CuentaContable { get; set; }
        public Nullable<int> IdTipoEmpleadoAplica { get; set; }
        public bool Activo { get; set; }
    
        public virtual TiposConceptos TiposConceptos { get; set; }
        public virtual TiposEmpleados TiposEmpleados { get; set; }
        public virtual ICollection<DetallesNomina> DetallesNomina { get; set; }
    }
}
