//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTECAM.Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionesPartidas
    {
        public ConfiguracionesPartidas()
        {
            this.Partidas = new HashSet<Partidas>();
        }
    
        public int Id { get; set; }
        public int Anio { get; set; }
        public int TamanioClave { get; set; }
        public string ExpresionRegular { get; set; }
        public int PosicionInicialEnClavePresupuestal { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Partidas> Partidas { get; set; }
    }
}
