//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTECAM.Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesNomina
    {
        public int Id { get; set; }
        public int IdNomina { get; set; }
        public int IdEmpleado { get; set; }
        public int IdTipoEmpleado { get; set; }
        public int IdConcepto { get; set; }
        public decimal Monto { get; set; }
        public string CentroCosto { get; set; }
    
        public virtual Conceptos Conceptos { get; set; }
        public virtual Nomina Nomina { get; set; }
        public virtual TiposEmpleados TiposEmpleados { get; set; }
    }
}
