//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTECAM.Presupuesto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidas
    {
        public Partidas()
        {
            this.ClavesPresupuestales = new HashSet<ClavesPresupuestales>();
        }
    
        public int Id { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public int IdConfiguracionPartida { get; set; }
    
        public virtual ConfiguracionesPartidas ConfiguracionesPartidas { get; set; }
        public virtual ICollection<ClavesPresupuestales> ClavesPresupuestales { get; set; }
    }
}
