//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTECAM.Presupuesto.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ISSSTECAM.Presupuesto.Entidades;
    
    public partial class PresupuestoDBEntities : DbContext
    {
        public PresupuestoDBEntities()
            : base("name=PresupuestoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CentrosCostos> CentrosCostos { get; set; }
        public DbSet<Partidas> Partidas { get; set; }
        public DbSet<Actividades> Actividades { get; set; }
        public DbSet<ConfiguracionesActividades> ConfiguracionesActividades { get; set; }
        public DbSet<ConfiguracionesPartidas> ConfiguracionesPartidas { get; set; }
        public DbSet<ConfiguracionesProgramas> ConfiguracionesProgramas { get; set; }
        public DbSet<ConfiguracionesProyectos> ConfiguracionesProyectos { get; set; }
        public DbSet<Programas> Programas { get; set; }
        public DbSet<Proyectos> Proyectos { get; set; }
        public DbSet<ClavesPresupuestales> ClavesPresupuestales { get; set; }
        public DbSet<Conceptos> Conceptos { get; set; }
        public DbSet<Nomina> Nomina { get; set; }
        public DbSet<TiposConceptos> TiposConceptos { get; set; }
        public DbSet<TiposEmpleados> TiposEmpleados { get; set; }
        public DbSet<DetallesNomina> DetallesNomina { get; set; }
    }
}
