//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ISSSTECAM.RH.ServiciosWeb")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vstEmpleadoDTO", Namespace="http://schemas.datacontract.org/2004/07/ISSSTECAM.RH.Entidades")]
    [System.SerializableAttribute()]
    public partial class vstEmpleadoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCostoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCosto {
            get {
                return this.IdCostoField;
            }
            set {
                if ((this.IdCostoField.Equals(value) != true)) {
                    this.IdCostoField = value;
                    this.RaisePropertyChanged("IdCosto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoEmpleado {
            get {
                return this.IdTipoEmpleadoField;
            }
            set {
                if ((this.IdTipoEmpleadoField.Equals(value) != true)) {
                    this.IdTipoEmpleadoField = value;
                    this.RaisePropertyChanged("IdTipoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCosto {
            get {
                return this.NombreCostoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCostoField, value) != true)) {
                    this.NombreCostoField = value;
                    this.RaisePropertyChanged("NombreCosto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RH.ServiciosWeb.IServicioEmpleados")]
    public interface IServicioEmpleados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleados/GetData", ReplyAction="http://tempuri.org/IServicioEmpleados/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleados/GetData", ReplyAction="http://tempuri.org/IServicioEmpleados/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleados/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServicioEmpleados/GetDataUsingDataContractResponse")]
        ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.CompositeType GetDataUsingDataContract(ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleados/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServicioEmpleados/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.CompositeType> GetDataUsingDataContractAsync(ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleados/ObtenerPorNumeroEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleados/ObtenerPorNumeroEmpleadoResponse")]
        ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.vstEmpleadoDTO ObtenerPorNumeroEmpleado(string numeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleados/ObtenerPorNumeroEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleados/ObtenerPorNumeroEmpleadoResponse")]
        System.Threading.Tasks.Task<ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.vstEmpleadoDTO> ObtenerPorNumeroEmpleadoAsync(string numeroEmpleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEmpleadosChannel : ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.IServicioEmpleados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEmpleadosClient : System.ServiceModel.ClientBase<ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.IServicioEmpleados>, ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.IServicioEmpleados {
        
        public ServicioEmpleadosClient() {
        }
        
        public ServicioEmpleadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEmpleadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpleadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.CompositeType GetDataUsingDataContract(ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.CompositeType> GetDataUsingDataContractAsync(ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.vstEmpleadoDTO ObtenerPorNumeroEmpleado(string numeroEmpleado) {
            return base.Channel.ObtenerPorNumeroEmpleado(numeroEmpleado);
        }
        
        public System.Threading.Tasks.Task<ISSSTECAM.Presupuesto.Web.RH.ServiciosWeb.vstEmpleadoDTO> ObtenerPorNumeroEmpleadoAsync(string numeroEmpleado) {
            return base.Channel.ObtenerPorNumeroEmpleadoAsync(numeroEmpleado);
        }
    }
}
